# Dependencies
markdown:         kramdown
highlighter:      rouge
remote_theme:     https://github.com/fongandrew/hydeout/

# Setup
title:            The Code Manual
tagline:          'Madej''s thoughts not only about coding'
description:      'Madej''s thoughts not only about coding'
url:              https://kmadof.github.io
baseurl:          
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Krzysztof Madej'
  url:            https://twitter.com/kmadof

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

hydeout:
  repo:            https://github.com/kmadof

linkedin:          https://www.linkedin.com/in/krzysztof-madej/
twitter_link:      https://twitter.com/kmadof

# Google services
google_analytics: UA-88818077-1

disqus:
  shortname: krzysztof_madej

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-twitter-plugin

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
collections:
  links:
    output: true