# Site setings
name: 'The Code Manual'
description: 'Make everything with code'
meta_description: 'Blog about programming, DevOps and software architecture'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'kmadof.jpg'
  greetings: "Hi there! I'm Krzysztof Madej and I work as .NET developer implementing Azure cloud based solutions and improving DevOps practices using Azure DevOps"
favicon: 'assets/images/favicon.png'
baseurl: 
production_url: https://thecodemanual.pl/
disqus: 'thecodemanual'
#mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
# Add your GA Tracking Id
ga_analytics: UA-88818077-1

# Contact form setings
email: youremail@email.com
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'kmadof'
#facebook: 'username'
github: 'kmadof'
#codepen: 'username'
#dribbble: 'username'
#medium: '@username'
#instagram: 'username'
#pinterest: 'username'
linkedin: 'krzysztof-madej'
#producthunt: '@username'
#quora: 'username'

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  # - text: Style Guide
  #   url: /style-guide
  # - text: Contact Me
  #   url: /contact
  - text: Search
    url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:year/:month/:day/:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
